---
- name: Install git
  dnf:
    name: git
    state: present

- name: Install python3-pip
  dnf:
    name: python3-pip
    state: present

- name: Clone Django app
  git:
    repo: "{{ app_repo }}"
    dest: "{{ app_path }}"
    version: tester
    force: yes

- name: Create virtualenv
  command:
    cmd: python3 -m venv "{{ app_path }}/venv"
    creates: "{{ app_path }}/venv"

- name: Install pip packages in virtualenv
  pip:
    requirements: "{{ app_path }}/requirements.txt"
    virtualenv: "{{ app_path }}/venv"

- name: Set ALLOWED_HOSTS
  lineinfile:
    path: "{{ app_path }}/albatross/settings.py"
    regexp: 'ALLOWED_HOSTS'
    line: 'ALLOWED_HOSTS = ["*"]'

- name: Fix settings.py indentation
  shell: |
    sed -i 's/^CSRF_TRUSTED_ORIGINS/    CSRF_TRUSTED_ORIGINS/' /home/shino/albatross-tester/albatross/settings.py
    sed -i 's/^ALLOWED_HOSTS/    ALLOWED_HOSTS/' /home/shino/albatross-tester/albatross/settings.py

- name: Run migrations
  command:
    cmd: "{{ app_path }}/venv/bin/python manage.py migrate"
    chdir: "{{ app_path }}"

- name: Set SELinux context for venv
  command:
    cmd: chcon -R -t bin_t "{{ app_path }}/venv/"

- name: Copy gunicorn service file
  copy:
    src: gunicorn.service
    dest: /etc/systemd/system/gunicorn.service
    owner: root
    group: root
    mode: '0644'

- name: Enable and start gunicorn
  systemd:
    name: gunicorn
    enabled: yes
    state: started
    daemon_reload: yes

- name: Deploy .env file
  template:
    src: .env.j2
    dest: "{{ app_path }}/.env"
    owner: "{{ ansible_user }}"
    mode: '0600'
