---
- name: Nginx setup
  hosts: nginx
  become: yes
  roles:
    - nginx

- name: Apache setup
  hosts: apache
  become: yes
  tasks:
    - name: Install httpd
      dnf:
        name: httpd
        state: present
    - name: Start httpd
      service:
        name: httpd
        state: started
        enabled: yes
      

- name: MySQL setup
  hosts: mysql           
  become: yes
  tasks: 
    - name: Install mariadb-server
      dnf:
        name: mariadb-server
        state: present
    - name: Start mariadb
      service:
        name: mariadb
        state: started
        enabled: yes

