---
- name: Dockerセットアップ
  hosts: nginx
  become: yes
  roles:
    - docker
  tags:
    - docker

- name: アプリケーションセットアップ
  hosts: nginx
  become: yes
  roles:
    - web
    - db
  tags:
    - app

- name: 監視環境セットアップ
  hosts: nginx
  become: yes
  roles:
    - prometheus
    - grafana
    - loki
    - promtail
    - alertmanager
  tags:
    - monitoring

- name: Node Exporterセットアップ
  hosts: all
  become: yes
  roles:
    - node_exporter

- name: Cloudflaredセットアップ
  hosts: nginx
  become: yes
  roles:
    - cloudflared

