---
- name: Nginx setup
  hosts: nginx
  become: yes
  roles:
    - nginx
  tasks:
    - name: Open port 80
      ansible.posix.firewalld:
        port: 80/tcp
        permanent: yes
        state: enabled
        immediate: yes

    - name: Allow nginx proxy
      ansible.posix.seboolean:
        name: httpd_can_network_connect
        state: yes
        persistent: yes


- name: Apache setup
  hosts: apache
  become: yes
  tasks:
    - name: Install httpd
      dnf:
        name: httpd
        state: present
    - name: Start httpd
      service:
        name: httpd
        state: started
        enabled: yes


- name: PostgreSQL setup
  hosts: mysql
  become: yes
  roles:
    - postgresql
    - pg_backup
  tags:
    - postgresql

- name: Gunicorn setup
  hosts: apache
  become: yes
  roles:
    - gunicorn
  tags:
    - gunicorn

- name: Prometheus setup
  hosts: nginx
  become: yes
  roles:
    - prometheus
  tags:
    - prometheus

- name: Alertmanager setup
  hosts: nginx
  become: yes
  roles:
    - alertmanager
  tags:
    - alertmanager

- name: Node Exporter setup
  hosts: all
  become: yes
  roles:
    - node_exporter

- name: Grafana setup
  hosts: nginx
  become: yes
  roles:
    - grafana
  tags:
    - grafana

- name: Docker setup
  hosts: nginx
  become: yes
  roles:
    - docker
  tags:
    - docker

- name: Cloudflared setup
  hosts: nginx
  become: yes
  roles:
    - cloudflared

- name: Loki setup
  hosts: nginx
  become: yes
  roles:
    - loki
  tags:
    - loki
