---
- name: Remove podman-docker
  dnf:
    name: podman-docker
    state: absent

- name: Install Docker
  dnf:
    name: docker-ce
    state: present

- name: Install docker-compose
  get_url:
    url: "https://github.com/docker/compose/releases/latest/download/docker-compose-linux-x86_64"
    dest: /usr/local/bin/docker-compose
    mode: '0755'

- name: Enable and start podman socket
  systemd:
    name: podman.socket
    state: started
    daemon_reload: yes

- name: Copy docker-compose file
  copy:
    src: docker-compose.yml
    dest: "{{ docker_app_user_home }}/docker-compose.yml"

- name: Copy Dockerfile
  copy:
    src: Dockerfile
    dest: "{{ docker_app_user_home }}/Dockerfile"

- name: Copy requirements.txt
  copy:
    src: requirements.txt
    dest: "{{ docker_app_user_home }}/requirements.txt"

- name: Deploy .env file
  template:
    src: .env.j2
    dest: "{{ docker_app_user_home }}/.env"
    mode: '0640'

- name: Run docker-compose
  command:
    cmd: /usr/local/bin/docker-compose up -d
    chdir: "{{ docker_app_user_home }}"
