---
- name: Install Docker
  dnf:
    name: docker
    state: present

- name: Install docker-compose
  get_url:
    url: https://github.com/docker/compose/releases/download/v2.24.0/docker-compose-linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: '0755'

- name: Enable and start podman socket
  systemd:
    name: podman.socket
    state: started
    daemon_reload: yes

- name: Copy docker-compose file
  copy:
    src: docker-compose.yml
    dest: /home/shino/docker-compose.yml

- name: Copy Dockerfile
  copy:
    src: Dockerfile
    dest: /home/shino/Dockerfile

- name: Copy requirements.txt
  copy:
    src: requirements.txt
    dest: /home/shino/requirements.txt

- name: Run docker-compose
  command:
    cmd: /usr/local/bin/docker-compose up -d
    chdir: /home/shino

