name: Auto Patch

on:
  schedule:
    - cron: '0 0 * * 0' # 毎週日曜日0時に実行
  workflow_dispatch:  # 手動実行も可能

jobs:
  patch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed225519

      - name: Install ansible
        run: pip install ansible

      - name: Run patch playbook
        run: ansible-playbook patch.yml -i inventory
